Add psalm
sonata-project/sonata-doctrine-extensions pull request #252
Opened 2020-10-15 20:57 UTC by core23

## Subject

I am targeting this branch, because this is BC.

2020-10-16 10:11 UTC, OskarStark approved these changes

2020-10-17 09:51 UTC, greg0ire approved these changes
For bonus points, let's analyze the `tests` directory too?

2020-10-17 18:41 UTC, franmomu requested changes
Psalm is not running because of mongodb extension: https://github.com/sonata-project/sonata-doctrine-extensions/pull/252/checks?check_run_id=1261363676

2020-11-03 10:40 UTC, core23 commented
After merging this, the file can be managed by https://github.com/sonata-project/dev-kit/pull/1238

2020-11-03 11:15 UTC, OskarStark approved these changes

2020-11-03 11:15 UTC, merged